[project]
name = "pg-forge"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64", "linux-aarch64"]

[dependencies]
rattler-build = ">=0.39.0,<0.40"
