context:
  name: psycopg
  version: "3.2.6"

recipe:
  name: psycopg-split
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: psycopg-c

    build:
      script: ${{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

    source:
      url: https://pypi.org/packages/source/p/psycopg-c/psycopg_c-${{ version }}.tar.gz
      sha256: b5fd4ce70f82766a122ca5076a36c4d5818eaa9df9bf76870bc83a064ffaed3a

    requirements:
      build:
        - ${{ compiler('c') }}
        # - ${{ stdlib("c") }}
      host:
        - python
        - pip
        - libpq
        - setuptools
      run:
        - libpq
        - python

    tests:
      - script:
          - pip check
        requirements:
          run:
            - pip
    about:
      license_file: LICENSE.txt

  - package:
      name: psycopg

    source:
      url: https://pypi.org/packages/source/p/psycopg/psycopg-${{ version }}.tar.gz
      sha256: 16fa094efa2698f260f2af74f3710f781e4a6f226efe9d1fd0c37f384639ed8a

    build:
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        # - tzdata  # [win]
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('psycopg-c', upper_bound='x.x.x.x.x.x') }}
        # for python <3.13 but keeping it for all to stay noarch: python
        - typing-extensions >=4.6
        # - tzdata  # [win]
        # - __unix  # [unix]
        # - __win  # [win]
    tests:
      - python:
          imports:
            - psycopg
            - psycopg.pq
            - psycopg_c 
    about:
      license_file: LICENSE.txt
about:
  homepage: https://psycopg.org/psycopg3/
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg 3 is a newly designed PostgreSQL database adapter for the Python
    programming language. Psycopg 3 presents a familiar interface for everyone
    who has used Psycopg 2 or any other DB-API 2.0 database adapter, but allows
    to use more modern PostgreSQL and Python features.
  license: LGPL-3.0-or-later
  documentation: https://www.psycopg.org/psycopg3/docs/
  repository: https://github.com/psycopg/psycopg/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - xylar